_use:
  release:
    name: %%RELEASE_NAME%%
    namespace: %%RELEASE_NAMESPACE%%
    chart: %%RELEASE_CHART%%
    version: %%RELEASE_VERSION%%
    createNamespace: true

  repositories_sync: true
  repositories:
    - name: %%RELEASE_REPOSITORY%%
      url: https://release.charts.url

## === %%RELEASE_NAME%% specific settings ===
##
# _set:
#   podAntiAffinity:
#     # soft/true and hard, other than this disables affinity
#     enabled: true
#     weight: 1

#   autoscaling:
#     enabled: true
#     minReplicas: 1
#     maxReplicas: 3

#   resources:
#     requests:
#       cpu: 100m
#       memory: 90Mi
#     limits:
#       cpu: 200m
#       memory: 250Mi

#   service:
#     annotations: {}

## === Release predefined defaults ===
##
# _default:
#   podAntiAffinity:
#     topologyKey: kubernetes.io/hostname
#     matchExpressions:
#       - key: app.kubernetes.io/name
#         operator: In
#         values:
#           - %%RELASE_NAME%%
