_setup:
  release:
    name: %%RELEASE_NAME%%
    namespace: %%RELEASE_NAMESPACE%%
    chart: %%RELEASE_CHART%%
    version: %%RELEASE_VERSION%%
    createNamespace: true

## Preset default values (common between releases)
## Note: trim down for a specific release
##
_preset:
  ## Default enablers
  ## default_myoption: true
  # Pod Anti Affinity true/soft/hard (true equals soft)
  anti_affinity: true
  anti_affinity_weight: 1
  autoscale: true
  autoscale_min: 1
  autoscale_max: 3
  request_cpu: 100m
  request_memory: 100Mi
  limit_cpu: 200m
  limit_memory: 250Mi
  service_annotations: {}

## Default enablers configuration (maps of default values)
## Note: use default_myoption: true to enable
##
# _default:
#   myoption:
