bases:
  - ../../templates/env.yaml.gotmpl
---

## Repositories section
{{- if .Values._setup.update_repos }}
repositories:
- name: %%REPOSITORY_NAME%%
  url: %%REPOSITORY_URL%%
{{- end }}

## Template helpers section
{{- $release := tpl (readFile "../../templates/_release.tpl") . -}}

## Releases section
releases:
## Default release
- {{- $release | nindent 2 }}
