bases:
  - ../../templates/env.yaml.gotmpl
---

## Repositories
{{- if .Values._set.repositories.update }}
repositories:
{{- range $name, $url := .Values._set.repositories.map }}
- name: {{ $name }}
  url: {{ $url }}
{{- end }}
{{- end }}

## Formulas
{{- $release := tpl (readFile "../../templates/release.tpl") (dict "context" $) -}}

## Releases
releases:
# renders the default release
- {{- $release | nindent 2 -}}
