_use:
  release:
    name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.6.1
    createNamespace: true
    labels:
      bundle: cert-manager

  repositories_sync: true
  repositories:
    - name: jetstack
      url: https://charts.jetstack.io
    - name: bedag
      url: https://bedag.github.io/helm-charts

## === cert-manager release specific settings ===
##
_set:
  # Apply jetstack CRDs after helmfile sync
  postsync_crds: true

  # Sets the default ingress shim to use
  ingress_shim: letsencrypt

  # Let's encrypt configuration
  letsencrypt:
    ## Set acme_email when installing letsencrypt issuers
    # acme_email: email@tld.com
    environment: prod # or staging
    challange: http01
    ## Default ingress class
    ingress_class: nginx

  # Installed cluster issuers
  cluster_issuers:
    letsencrypt_http01: true
    # letsencrypt_dns: true
    # route53: true

## === Release default settings ===
##
_default:
  # Default ingress shim for letsencrypt 
  letsencrypt:
    ingressShim: |
      defaultIssuerName: "letsencrypt-{{ .Values._set.letsencrypt.challange }}-{{ .Values._set.letsencrypt.environment }}"
      defaultIssuerKind: ClusterIssuer
      defaultIssuerGroup: cert-manager.io
