bases:
  - ../../templates/env.yaml.gotmpl
---

## Repositories
{{- if .Values._use.repositories_sync }}
repositories: {{- .Values._use.repositories | toYaml | nindent 2 }}
{{- end }}

## Formulas
{{- $release := tpl (readFile "../../templates/release.tpl") (dict "context" $) -}}

## Releases
releases:
- {{- $release | nindent 2 -}}
